const { askAgent } = require("./llmService");

/**
 * Challenges an initial verdict by looking for flaws, alternative explanations, or missing context.
 * 
 * @param {Object} claim - The claim being investigated.
 * @param {Object} verdictData - The initial verdict generated by the investigator.
 * @param {Array} evidence - The evidence used to generate the initial verdict.
 * @returns {Promise<{hasObjection: boolean, objection: string, suggestedFollowUpQuery: string}>}
 */
async function challengeVerdict(claim, verdictData, evidence) {
    const prompt = `
You are a highly skeptical adversarial reviewer. Your job is to poke holes in the following investigator's verdict. 
Look for alternative explanations, missing context, timing issues (e.g. "could this be outdated?"), or over-reliance on weak sources.

Claim being investigated: "${claim.text}"
Investigator's Verdict: ${verdictData.verdict} (Confidence: ${verdictData.confidence}%)
Investigator's Reasoning: "${verdictData.reasoning}"

Evidence used:
${JSON.stringify(evidence.map(e => ({ title: e.title, snippet: e.snippet })), null, 2)}

Is there a significant flaw or alternative explanation that warrants further investigation? If the verdict is extremely solid, you can agree with it, but you should lean towards skepticism.

Return ONLY valid JSON in this exact shape, with no extra text, no markdown formatting, no explanation:
{
  "hasObjection": true or false,
  "objection": "If true, explain the specific flaw or alternative explanation. If false, leave empty.",
  "suggestedFollowUpQuery": "If true, provide ONE specific Google search query to resolve this objection."
}
`;

    const rawResponse = await askAgent(prompt);
    
    try {
        const clean = rawResponse.replace(/```json|```/g, "").trim();
        const parsed = JSON.parse(clean);
        
        if (typeof parsed.hasObjection !== 'boolean') {
            throw new Error("Missing or invalid 'hasObjection' boolean in response");
        }
        return parsed;
    } catch (error) {
        console.error("Failed to parse challengeVerdict JSON. Raw response:", rawResponse);
        // Fallback: if we fail to parse, assume no objection to avoid crashing the pipeline
        return { hasObjection: false, objection: "", suggestedFollowUpQuery: "" };
    }
}

module.exports = { challengeVerdict };
